language: ruby

rvm:
  - 2.4.0

sudo: false

before_install:
  - gem update --system

before_script:
  - psql -c 'create database classroom_test;' -U postgres

script:
  - ./script/cibuild

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

services:
  - postgresql
  - redis-server

env:
  global:
    - GITHUB_CLIENT_ID=client_id
    - GITHUB_CLIENT_SECRET=client_secret
    - WEBHOOK_SECRET=abcdefg
    - CLASSROOM_WEBHOOK_URL_PREFIX="https://example.com/github/hooks"

notifications:
  email: false
